import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./Provider";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { inter } from "./ui/fonts";
import Logo from "./photos/Logo.png";
import Image from "next/image";
import Navbar from "./Navbar";
import NavbarForPhone from "./NavbarForPhone";
import Hamburger from "./Hamburger";
import Cart from "./Cart";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="flex justify-between items-center py-4 h-16 px-[120px]">
            <div>
              <Image alt="#" src={Logo} />
            </div>
            <Navbar />
            <NavbarForPhone />
            <div className="hidden lg:flex gap-2 ">
              <SignedOut>
                <SignInButton>
                  <button
                    className={`border-gray-200 border-2 rounded-md py-2 px-4 ${inter.className} cursor-pointer`}
                  >
                    Sign In
                  </button>
                </SignInButton>
                <SignUpButton>
                  <button
                    className={`bg-[#10B981] py-2 px-4 rounded-md ${inter.className} text-white cursor-pointer`}
                  >
                    Sign Up
                  </button>
                </SignUpButton>
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </div>
            <Hamburger />
          </header>
          <div className="py-2 px-[120px] sm:block hidden">
            <div className="w-full h-[0.3px] bg-gray-300"></div>
          </div>
          <Providers>{children}</Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
